# dummy-lms-project/.agent_blueprint.yml
project_type: fullstack_react_node

required_files:
  - name: Dockerfile.frontend
    location: frontend/
  - name: Dockerfile.backend
    location: backend/
  - name: docker-compose.yml
    location: ./
  - name: .gitignore
    location: ./
  - name: .env.example
    location: ./

code_rules:
  - file: backend/server.js
    audits:
      - feature: health_check_endpoint
        prompt: "Does this Express.js code contain a '/health' or '/status' endpoint? Respond with only YES or NO."
      - feature: structured_logging
        prompt: "Does this Node.js code use a structured logging library like Winston or Morgan instead of only console.log? Respond with only YES or NO."
  - file: frontend/src/App.js
    audits:
      - feature: no_hardcoded_urls
        prompt: "Does this React code contain a hardcoded fetch URL that doesn't use process.env? Respond with only YES or NO."
      - feature: use_effect_dependencies
        prompt: "In this React code, is there a useEffect hook that is missing a dependency array `[]`? Respond with only YES or NO."